# Generated by Django 5.2.16 on 2026-07-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto')], db_index=True, default='PENDIENTE', max_length=12)),
                ('clave_acceso', models.CharField(blank=True, db_index=True, max_length=49, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('establecimiento', models.CharField(max_length=3)),
                ('punto_emision', models.CharField(max_length=3)),
                ('secuencial', models.CharField(max_length=9)),
                ('ambiente', models.CharField(default='1', max_length=1)),
                ('cliente_identificacion', models.CharField(max_length=20)),
                ('cliente_tipo_identificacion', models.CharField(default='05', max_length=2)),
                ('cliente_razon_social', models.CharField(max_length=300)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('cliente_direccion', models.CharField(blank=True, max_length=300)),
                ('cliente_telefono', models.CharField(blank=True, max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payload', models.JSONField(default=dict)),
                ('xml_path', models.CharField(blank=True, max_length=500)),
                ('xml_autorizado_path', models.CharField(blank=True, max_length=500)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('mensaje_sri', models.TextField(blank=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'created_at'], name='facturacion_estado_88fc09_idx')],
            },
        ),
    ]
