# Generated by Django 6.0.6 on 2026-06-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Nuestra Tienda', max_length=80, verbose_name='Nombre de la tienda')),
                ('slogan', models.CharField(blank=True, default='Explora nuestro catálogo y solicita tu pedido en minutos', max_length=160, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('color_primario', models.CharField(default='#B5441B', help_text='Ej: #B5441B', max_length=7, verbose_name='Color principal (hex)')),
                ('color_oscuro', models.CharField(default='#231A10', help_text='Ej: #231A10', max_length=7, verbose_name='Color oscuro (hex)')),
                ('banner_activo', models.BooleanField(default=True, verbose_name='Mostrar banner promocional')),
                ('banner_titulo', models.CharField(default='Envío gratis en pedidos mayores a $50', max_length=120, verbose_name='Título del banner')),
                ('banner_subtitulo', models.CharField(blank=True, default='Válido para entregas dentro de la ciudad · Coordina con el negocio', max_length=200, verbose_name='Subtítulo del banner')),
                ('banner_cta', models.CharField(default='Ver productos', max_length=40, verbose_name='Texto del botón del banner')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Número WhatsApp (con código de país, ej: 593999999999)')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuración del negocio',
            },
        ),
    ]
