# Generated by Django 6.0.6 on 2026-06-25 01:27
# Editada a mano: las columnas de ConfigNegocio se agregan de forma idempotente
# porque algunas ya existían en producción (drift entre el modelo y la BD).

import django.db.models.deletion
from django.db import migrations, models


# Campos de ConfigNegocio que esta migración declara. En producción algunos
# (o todos) ya existen, así que se agregan solo si faltan.
CONFIG_FIELDS = [
    'color_fondo', 'color_navbar', 'hero_imagen', 'hero_titulo',
    'porque_1_icono', 'porque_1_texto', 'porque_1_titulo',
    'porque_2_icono', 'porque_2_texto', 'porque_2_titulo',
    'porque_3_icono', 'porque_3_texto', 'porque_3_titulo',
    'porque_activo', 'porque_titulo',
    'sobre_activo', 'sobre_imagen', 'sobre_texto', 'sobre_titulo',
]


def add_missing_config_columns(apps, schema_editor):
    """Agrega a billing_confignegocio solo las columnas que aún no existen.
    Intenta cada columna en un savepoint; si ya existe, la salta. Idempotente
    en Postgres (producción) y SQLite (local/nuevo)."""
    from django.db import transaction
    from django.db.utils import ProgrammingError, OperationalError

    Model = apps.get_model('billing', 'ConfigNegocio')
    conn = schema_editor.connection

    def already_exists(err):
        msg = str(err).lower()
        return 'exist' in msg or 'duplicate' in msg

    for name in CONFIG_FIELDS:
        field = Model._meta.get_field(name)
        try:
            with transaction.atomic(using=conn.alias):
                schema_editor.add_field(Model, field)
        except (ProgrammingError, OperationalError) as err:
            if not already_exists(err):
                raise

    # Ensanchar 'logo' (max_length 100 -> 500). Solo Postgres; ignora si falla.
    if conn.vendor == 'postgresql':
        try:
            with transaction.atomic(using=conn.alias):
                schema_editor.execute(
                    'ALTER TABLE %s ALTER COLUMN "logo" TYPE varchar(500)'
                    % schema_editor.quote_name(Model._meta.db_table)
                )
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_confignegocio'),
    ]

    operations = [
        # --- Nuevos en todos lados (sin conflicto) ---
        migrations.AddField(
            model_name='brand',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text='Con código de país, ej: 593999999999. Recibe los pedidos de esta tienda.', max_length=20, verbose_name='WhatsApp de la tienda'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='products/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='billing.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['order', 'id'],
            },
        ),
        # --- ConfigNegocio: primero declaramos los campos SOLO en el estado de
        #     Django (sin tocar la BD); luego un RunPython agrega en la BD solo
        #     las columnas que falten (idempotente frente a producción). ---
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(model_name='confignegocio', name='color_fondo',
                    field=models.CharField(default='#F8F3EE', help_text='Fondo general de la tienda', max_length=7, verbose_name='Color de fondo (hex)')),
                migrations.AddField(model_name='confignegocio', name='color_navbar',
                    field=models.CharField(default='#231A10', help_text='Barra de navegación superior', max_length=7, verbose_name='Color del navbar (hex)')),
                migrations.AddField(model_name='confignegocio', name='hero_imagen',
                    field=models.ImageField(blank=True, max_length=500, null=True, upload_to='config/', verbose_name='Imagen de fondo del hero')),
                migrations.AddField(model_name='confignegocio', name='hero_titulo',
                    field=models.CharField(blank=True, default='Encuentra lo que buscas', max_length=100, verbose_name='Título del hero')),
                migrations.AddField(model_name='confignegocio', name='porque_1_icono',
                    field=models.CharField(blank=True, default='bi-truck', max_length=50, verbose_name='Ícono 1 (Bootstrap Icons)')),
                migrations.AddField(model_name='confignegocio', name='porque_1_texto',
                    field=models.CharField(blank=True, default='Entrega a domicilio en toda la ciudad.', max_length=200, verbose_name='Texto 1')),
                migrations.AddField(model_name='confignegocio', name='porque_1_titulo',
                    field=models.CharField(blank=True, default='Envío rápido', max_length=80, verbose_name='Título 1')),
                migrations.AddField(model_name='confignegocio', name='porque_2_icono',
                    field=models.CharField(blank=True, default='bi-shield-check', max_length=50, verbose_name='Ícono 2')),
                migrations.AddField(model_name='confignegocio', name='porque_2_texto',
                    field=models.CharField(blank=True, default='Productos con garantía directa del fabricante.', max_length=200, verbose_name='Texto 2')),
                migrations.AddField(model_name='confignegocio', name='porque_2_titulo',
                    field=models.CharField(blank=True, default='Garantía', max_length=80, verbose_name='Título 2')),
                migrations.AddField(model_name='confignegocio', name='porque_3_icono',
                    field=models.CharField(blank=True, default='bi-headset', max_length=50, verbose_name='Ícono 3')),
                migrations.AddField(model_name='confignegocio', name='porque_3_texto',
                    field=models.CharField(blank=True, default='Atención personalizada antes y después de tu compra.', max_length=200, verbose_name='Texto 3')),
                migrations.AddField(model_name='confignegocio', name='porque_3_titulo',
                    field=models.CharField(blank=True, default='Soporte', max_length=80, verbose_name='Título 3')),
                migrations.AddField(model_name='confignegocio', name='porque_activo',
                    field=models.BooleanField(default=False, verbose_name='Mostrar sección "Por qué elegirnos"')),
                migrations.AddField(model_name='confignegocio', name='porque_titulo',
                    field=models.CharField(blank=True, default='¿Por qué elegirnos?', max_length=100, verbose_name='Título')),
                migrations.AddField(model_name='confignegocio', name='sobre_activo',
                    field=models.BooleanField(default=False, verbose_name='Mostrar sección "Sobre nosotros"')),
                migrations.AddField(model_name='confignegocio', name='sobre_imagen',
                    field=models.ImageField(blank=True, max_length=500, null=True, upload_to='config/', verbose_name='Imagen')),
                migrations.AddField(model_name='confignegocio', name='sobre_texto',
                    field=models.TextField(blank=True, verbose_name='Texto')),
                migrations.AddField(model_name='confignegocio', name='sobre_titulo',
                    field=models.CharField(blank=True, default='Sobre nosotros', max_length=100, verbose_name='Título')),
                migrations.AlterField(model_name='confignegocio', name='logo',
                    field=models.ImageField(blank=True, max_length=500, null=True, upload_to='config/', verbose_name='Logo')),
            ],
        ),
        # Ahora el estado ya tiene los campos: agregamos en BD los que falten.
        migrations.RunPython(add_missing_config_columns, migrations.RunPython.noop),
    ]
