# Generated by Django 6.0.6 on 2026-07-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_estado_invoice_saldo_invoice_tipo_pago'),
        ('billing', '0009_confignegocio_color_texto'),
    ]

    operations = [
    ]
