# Generated by Django 6.0.6 on 2026-07-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_parcial_invoicepayment'),
        ('billing', '0010_merge_20260709_2241'),
    ]

    operations = [
    ]
