# Generated by Django 6.0.6 on 2026-07-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_merge_20260709_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accepts_promotions',
            field=models.BooleanField(default=True, help_text='Si está marcado, el cliente recibirá correos de promociones y ofertas.', verbose_name='Acepta recibir promociones'),
        ),
    ]
