# Generated by Django 6.0.6 on 2026-07-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_restyle_navy_palette'),
        ('billing', '0012_customer_accepts_promotions'),
    ]

    operations = [
    ]
