# Generated by Django 6.0.6 on 2026-07-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_merge_20260710_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='brands/', verbose_name='Logo'),
        ),
    ]
