# Generated by Django 6.0.6 on 2026-07-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_brand_logo'),
        ('billing', '0014_confignegocio_ruc_alter_auditlog_id_alter_brand_id_and_more'),
    ]

    operations = [
    ]
