# Generated by Django 6.0.6 on 2026-07-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_reviewimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('export_brand', 'Puede exportar marcas a Excel/PDF')], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='confignegocio',
            options={'permissions': [('descargar_reportes_financieros', 'Puede descargar reportes financieros en Excel/PDF')], 'verbose_name': 'Configuración del negocio', 'verbose_name_plural': 'Configuración del negocio'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('export_customer', 'Puede exportar clientes a Excel/PDF')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('export_invoice', 'Puede exportar/descargar facturas en Excel/PDF')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('export_product', 'Puede exportar productos a Excel/PDF')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('export_productgroup', 'Puede exportar grupos de productos a Excel/PDF')], 'verbose_name': 'Grupo de producto', 'verbose_name_plural': 'Grupos de productos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('export_supplier', 'Puede exportar proveedores a Excel/PDF')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
