# Generated by Django 6.0.6 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_remove_orphaned_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelverificationcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelverificationcode',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
