# Generated by Django 6.0.6 on 2026-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_panelverificationcode_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que el cliente aceptó los Términos y Condiciones y la Política de Privacidad al registrarse.', null=True, verbose_name='Términos y privacidad aceptados el'),
        ),
    ]
