# Generated by Django 6.0.6 on 2026-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_customer_terms_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/', verbose_name='Imagen del producto'),
        ),
    ]
