# Generated by Django 6.0.6 on 2026-07-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocompra',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor abonado'),
        ),
    ]
