[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi --log-file -"
preDeployCommand = "python manage.py migrate --noinput"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
