# Generated by Django 6.0.6 on 2026-07-12 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0004_alter_purchase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='N° de cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de la cuota')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='purchasing.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Cuota de compra',
                'verbose_name_plural': 'Cuotas de compra',
                'ordering': ['compra', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de pago')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor abonado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos_compras.cuotacompra', verbose_name='Cuota')),
            ],
            options={
                'verbose_name': 'Pago de cuota de compra',
                'verbose_name_plural': 'Pagos de cuota de compra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuotacompra',
            constraint=models.UniqueConstraint(fields=('compra', 'numero'), name='unique_compra_numero_cuota'),
        ),
    ]
