"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
# Lee el archivo .env en desarrollo local. En producción (Railway/Render)
# las variables se configuran directo en el dashboard de la plataforma,
# así que si el archivo no existe simplemente no pasa nada.
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-v6jps@3n-%^faq4em1drs%0!tp_&0vo=2ho5zr6t-$-r_+27+*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Necesario para que Django confíe en peticiones POST (formularios, login)
# que llegan desde tu dominio real una vez que despliegues. Vacío en local.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Credenciales de PayPhone (Botón de Pago). Se obtienen en Payphone
# Developer al crear una aplicación de tipo "WEB".
PAYPHONE_TOKEN = env('PAYPHONE_TOKEN', default='')
PAYPHONE_STORE_ID = env('PAYPHONE_STORE_ID', default='')

# Email — en desarrollo imprime en la terminal (EMAIL_BACKEND=console).
# En Railway usa SendGrid automáticamente si SENDGRID_API_KEY está definida.
SENDGRID_API_KEY = env('SENDGRID_API_KEY', default='')
if SENDGRID_API_KEY:
    EMAIL_BACKEND = 'config.email_backend.SendGridEmailBackend'
else:
    EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='eliangaleaa18@gmail.com')
EMAIL_TIMEOUT = 10

# Email del proveedor que recibe la notificación cuando llega una solicitud nueva.
# Déjalo vacío para desactivar las notificaciones.
ADMIN_NOTIFICATION_EMAIL = env('ADMIN_NOTIFICATION_EMAIL', default='')
PAYPAL_CLIENT_ID = env('PAYPAL_CLIENT_ID', default='')
PAYPAL_SECRET = env('PAYPAL_SECRET', default='')
# Segundos de espera máx. por llamada a PayPal antes de abortar (evita colgar el worker).
PAYPAL_TIMEOUT = env.int('PAYPAL_TIMEOUT', default=20)
# Total de intentos por llamada (incluye el primero) ante fallos transitorios: timeout, 5xx, red caída.
PAYPAL_MAX_ATTEMPTS = env.int('PAYPAL_MAX_ATTEMPTS', default=3)
# Entorno de PayPal: 'sandbox' (pruebas) o 'live' (producción, dinero real).
# En producción DEBE ser 'live' y las credenciales deben ser las de la app Live,
# si no el SDK abre popups contra el entorno equivocado y falla la autenticación.
PAYPAL_MODE = env('PAYPAL_MODE', default='sandbox')
_PAYPAL_LIVE = PAYPAL_MODE.strip().lower() == 'live'
# Base de la API REST (server-side).
PAYPAL_API_BASE = 'https://api-m.paypal.com' if _PAYPAL_LIVE else 'https://api-m.sandbox.paypal.com'
# Base del SDK JS que carga el navegador (client-side).
PAYPAL_SDK_BASE = 'https://www.paypal.com' if _PAYPAL_LIVE else 'https://www.sandbox.paypal.com'
SITE_URL = env('SITE_URL', default='http://localhost:8000')

# Microservicio SRI — dejar SRI_MICRO_URL vacío para desactivar la integración
SRI_MICRO_URL = env('SRI_MICRO_URL', default='')
SRI_MICRO_API_KEY = env('SRI_MICRO_API_KEY', default='')
SRI_MICRO_TIMEOUT = env.int('SRI_MICRO_TIMEOUT', default=30)

# Microservicio de Notificaciones — dejar vacío para desactivar
NOTIF_MICRO_URL = env('NOTIF_MICRO_URL', default='')
NOTIF_MICRO_API_KEY = env('NOTIF_MICRO_API_KEY', default='')
NOTIF_MICRO_TIMEOUT = env.int('NOTIF_MICRO_TIMEOUT', default=10)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # apps users
    'billing',
    'purchasing',
    'storefront',
    'cobros',
    'pagos',
    'creditos_compras',
    'creditos_ventas',
    'reportes',
    'security',
    'widget_tweaks',
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.middleware.NoCachePanelMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'storefront.context_processors.config_negocio',
                'billing.context_processors.user_panel_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Lee la conexión completa desde la variable DATABASE_URL del .env, por ej:
# postgres://usuario:password@localhost:5432/sales_a2
# Así tu Postgres local y el de producción funcionan con el mismo código,
# solo cambia el valor de esta variable.

DATABASES = {
    'default': env.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde 'collectstatic' junta todos los estáticos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Cloudinary para almacenamiento de imágenes en producción.
# La librería cloudinary lee CLOUDINARY_URL del entorno automáticamente.
# Formato: cloudinary://api_key:api_secret@cloud_name
import os as _os
if _os.environ.get('CLOUDINARY_URL', ''):
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }

# Media files (Uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = '/panel/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = '/accounts/login/'

# Sesiones: expiran a las 8 horas de inactividad y al cerrar el navegador
SESSION_COOKIE_AGE = 8 * 60 * 60   # 8 horas en segundos
SESSION_SAVE_EVERY_REQUEST = True   # reinicia el contador con cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # cierra sesión al cerrar el navegador

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
