# Generated by Django 6.0.6 on 2026-07-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchase_parcial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Compra a proveedor', 'verbose_name_plural': 'Compras a proveedores'},
        ),
    ]
