# Generated by Django 6.0.6 on 2026-07-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('export_purchase', 'Puede exportar compras a Excel/PDF')], 'verbose_name': 'Compra a proveedor', 'verbose_name_plural': 'Compras a proveedores'},
        ),
    ]
