# Generated by Django 6.0.6 on 2026-07-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_remove_orphaned_permissions'),
        ('creditos_ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalCuotaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True, verbose_name='ID de orden (PayPal)')),
                ('cuota_ids', models.JSONField(verbose_name='IDs de cuotas incluidas')),
                ('captured', models.BooleanField(default=False, verbose_name='Capturada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_cuota_orders', to='billing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Orden PayPal de cuota(s)',
                'verbose_name_plural': 'Órdenes PayPal de cuotas',
            },
        ),
    ]
