# Generated by Django 6.0.6 on 2026-07-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_ventas', '0002_paypalcuotaorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotaventa',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo pendiente'),
        ),
        migrations.AlterField(
            model_name='cuotaventa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de la cuota'),
        ),
        migrations.AlterField(
            model_name='pagocuotaventa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor abonado'),
        ),
    ]
