# Generated by Django 6.0.6 on 2026-06-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_alter_customer_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='billing.customer', verbose_name='Cliente')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='billing.invoice', verbose_name='Factura generada')),
            ],
            options={
                'verbose_name': 'Solicitud de compra',
                'verbose_name_plural': 'Solicitudes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_details', to='billing.product', verbose_name='Producto')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='storefront.purchaserequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de solicitud',
                'verbose_name_plural': 'Detalles de solicitud',
            },
        ),
    ]
