# Generated by Django 6.0.6 on 2026-06-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'Revisión manual del proveedor'), ('tarjeta', 'Tarjeta de crédito/débito (PayPhone)')], default='manual', max_length=10, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payphone_client_transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID de transacción (nuestro)'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payphone_transaction_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID de transacción (PayPhone)'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
    ]
