# Generated by Django 6.0.6 on 2026-07-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada por el cliente')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
