# Generated by Django 6.0.6 on 2026-07-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_purchaserequest_paypal_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'Revisión manual del proveedor'), ('tarjeta', 'Tarjeta de crédito/débito (PayPhone)'), ('credito', 'Crédito directo (cuotas)')], default='manual', max_length=10, verbose_name='Método de pago'),
        ),
    ]
